name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  unit-test-code-coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Checkout
      uses: actions/checkout@v2
    # checkout the private repo containing the action to run
    - name: Checkout GitHub Action Repo
      uses: actions/checkout@v2
      with:
        repository: Hackathon2020GitHubActions/publish-test-result-action
        ref: master
        token: ${{ secrets.GIT_HUB_TOKEN }} # stored in GitHub secrets
        path: .github/actions/publish-test-result-action
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Unit Test Result
      uses: ./.github/actions/publish-test-result-action
      id: test-result-junit
      with:
        result-type: 'test'
        result-format: 'junit'
        report-path: 'target/surefire-reports'
        report-file-filter: '.*.xml'
    - name: Code Coverage Result
      uses: ./.github/actions/publish-test-result-action
      id: coverage-result-cobertura
      with:
        result-type: 'coverage'
        result-format: 'cobertura'
        report-path: 'target/site/cobertura'
        report-file-filter: '.*.xml'
    - name: Create Issue in Case of Test Case failures
      if: steps.test-result-junit.outputs.failed-tests != '0'
      uses: maxkomarychev/oction-create-issue@v0.7.1
      id: create-issue
      with:
        token: ${{ secrets.GIT_HUB_TOKEN }}
        title: "Automatic Issue: Unit Test Failures"
        body:  ${{ steps.test-result-junit.outputs.issue-body }}
        labels: "bug"
    - name: Check Code Coverage and fail if below threshold
      run: |
        CODE_COVERAGE=${{ steps.coverage-result-cobertura.outputs.code-coverage }}
        if [ $CODE_COVERAGE -lt 50 ]
          then
            echo "Code Coverage ${{ steps.coverage-result-cobertura.outputs.code-coverage }} is below threshold - 50"
            exit 1
        fi
        echo "Code Coverage ${{ steps.coverage-result-cobertura.outputs.code-coverage }} is above threshold - 50"
    - name: Check Unit Test and fail if failures
      if: steps.test-result-junit.outputs.failed-tests != '0'
      run: |
        echo "Failed Test Cases = ${{steps.test-result-junit.outputs.failed-tests}}"
        exit 1
    - name: Code Coverage Badge
      uses: RubbaBoy/BYOB@v1.1.0
      with:
        NAME: time
        LABEL: 'Code Coverage'
        STATUS: "${{ steps.coverage-result-cobertura.outputs.code-coverage }}%"
        COLOR: 00EEFF
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}